### ISSUE TITLE
Forbidden to download  Trinity2015.ova

### ISSUE THREAD

**Issue by ETaSky** [trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop#1]
Dear Developers,

When I tried to download the above VB image, I got following error msg:"
Forbidden
You don't have permission to access /Trinity/RNASEQ_WORKSHOP/Trinity2015.ova on this server.
"
I was wondering if there is anyway I could download the image to learn.
Thanks!

Jincheng

**Comment by brianjohnhaas** [comment]
Sorry about that!  Try it now.

best,

~brian

On Thu, Oct 29, 2015 at 3:53 PM, ETaSky notifications@github.com wrote:

> Dear Developers,
> 
> When I tried to download the above VB image, I got following error msg:"
> Forbidden
> You don't have permission to access
> /Trinity/RNASEQ_WORKSHOP/Trinity2015.ova on this server.
> "
> I was wondering if there is anyway I could download the image to learn.
> Thanks!
> 
> Jincheng
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/issues/1
> .

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas

**Comment by ETaSky** [comment]
Hi Brian,

Thanks a lot! I am still trying since last night. Now I can access the file but to download it is troublesome. It seems the serve that holds the file does not support "pause-continue" and it frequently shuts down the connection. So I always got like 188 MB, or 80 MB, and the further I went is about 1.8 GB and then the serve closed. So I am still trying.
Thanks!

Jincheng

**Comment by brianjohnhaas** [comment]
Interesting....  that shouldn't happen.

I'm bringing our IT group into the discussion, as they just set up this
site for me and it's supposed to be super-robust and super-fast.

best,

~b

On Fri, Oct 30, 2015 at 10:44 AM, ETaSky notifications@github.com wrote:

> Hi Brian,
> 
> Thanks a lot! I am still trying since last night. Now I can access the
> file but to download it is troublesome. It seems the serve that holds the
> file does not support "pause-continue" and it frequently shuts down the
> connection. So I always got like 188 MB, or 80 MB, and the further I went
> is about 1.8 GB and then the serve closed. So I am still trying.
> Thanks!
> 
> Jincheng
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/issues/1#issuecomment-152544571
> .

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas

**Comment by ETaSky** [comment]
Thanks! I am now trying to use firefox instead of chrome to download it. Somehow, firefox has a mechanism that can pick up the progress of a failed download. But using firefox seems to lose the connection very frequently. Very one minute or so, I have to restart the download to continue. Now, I have 490MB, and I am getting there. It might also be possible that it is the internet in my university that is causing the problem. I'll see what your IT guys say.
Thanks!

Jincheng

**Comment by ETaSky** [comment]
Just an update, after more than 50 clicks of restart in Firefox, I finally downloaded the whole stuff and successfully set up the VM machine. I'll start to work on it tomorrow and report if there are any more issues.
Thanks!

Jincheng
