### ISSUE TITLE
Error when running runTrinityDemo.pl 

### ISSUE THREAD

**Issue by sandrasan** [trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop#2]
Hi,

When trying to run runTrinityDemo.pl on my friend's laptop I get an error like so:

> Unrecognized escape \d passed through at ./runTrinityDemo.pl line 212.
> Global symbol "@F" requires explicit package name at ./runTrinityDemo.pl line 212.
> Global symbol "@F" requires explicit package name at ./runTrinityDemo.pl line 212.
> Execution of ./runTrinityDemo.pl aborted due to compilation errors.

The script is exactly the same as this one: https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/blob/master/runTrinityDemo.pl#L212

I've also noticed that the script doesn't match the scripts in these folders: https://github.com/trinityrnaseq/misc_tests/tree/master/rnaseq_workshop

How can we fix this?

**Comment by brianjohnhaas** [comment]
Hi,

Are you running this within the Virtualbox VM?

~b

On Tue, Mar 22, 2016 at 12:45 PM, sandrasan notifications@github.com
wrote:

> Hi,
> 
> When trying to run runTrinityDemo.pl on my friend's laptop I get an error
> like so:
> 
> Unrecognized escape \d passed through at ./runTrinityDemo.pl line 212.
> Global symbol "@F https://github.com/F" requires explicit package name
> at ./runTrinityDemo.pl line 212.
> Global symbol "@F https://github.com/F" requires explicit package name
> at ./runTrinityDemo.pl line 212.
> Execution of ./runTrinityDemo.pl aborted due to compilation errors.
> 
> The script is exactly the same as this one:
> https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/blob/master/runTrinityDemo.pl#L212
> 
> I've also noticed that the script doesn't match the scripts in these
> folders:
> https://github.com/trinityrnaseq/misc_tests/tree/master/rnaseq_workshop
> 
> How can we fix this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/issues/2

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas

**Comment by brianjohnhaas** [comment]
The materials and guides are here:
https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/wiki

in case that's helpful.

~b

**Comment by sandrasan** [comment]
Yes, running it in the VB! We tried it on a different computer and same error!

When I do `vboxmanage --version` I get `4.3.36_Ubuntur105129`

The .ova file was downloaded from [here](https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/wiki) (the link above).

**Comment by brianjohnhaas** [comment]
One last thing to try

Run 'git pull' in the workshop directory and then try again.

I'll look into this myself soon.

Best 

-Brian
(by iPhone)

**Comment by sandrasan** [comment]
I have done that originally and it says everything is up to date!

Thanks for your help!

**Comment by brianjohnhaas** [comment]
ok - I'll see if I can reproduce the issue

On Wed, Mar 23, 2016 at 8:44 AM, sandrasan notifications@github.com wrote:

> I have done that originally and it says everything is up to date!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/trinityrnaseq/RNASeq_Trinity_Tuxedo_Workshop/issues/2#issuecomment-200331172

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas

**Comment by brianjohnhaas** [comment]
I'll have the fix ready shortly.

**Comment by brianjohnhaas** [comment]
I updated the script.  Try running

   git pull

and this should update it, then you can continue on with running the demo.

sorry about the problem!

~brian

**Comment by sandrasan** [comment]
Everything works fine now! Cheers!

**Comment by brianjohnhaas** [comment]
Great!  Thanks for the update!
